// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWTz_GKBM00dXuXQslJr9XZPtNI-xC_MQ',
    appId: '1:970675942666:web:e313ce7ecd0902298a36f3',
    messagingSenderId: '970675942666',
    projectId: 'kiswa-6cd90',
    authDomain: 'kiswa-6cd90.firebaseapp.com',
    storageBucket: 'kiswa-6cd90.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDicu564C077MpusAFKU1xWEtPPdJEaVKQ',
    appId: '1:970675942666:android:5c29870ca88918bb8a36f3',
    messagingSenderId: '970675942666',
    projectId: 'kiswa-6cd90',
    storageBucket: 'kiswa-6cd90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwSdO8DwL6WK7d7hTj2xZxn2_8pilyChA',
    appId: '1:970675942666:ios:7c37fb381ec1a7b68a36f3',
    messagingSenderId: '970675942666',
    projectId: 'kiswa-6cd90',
    storageBucket: 'kiswa-6cd90.appspot.com',
    iosBundleId: 'com.example.kiswa',
  );
}
